name: build for atmega328p C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: update packages
      run: sudo apt update
    - name: install avr-gcc & avr-binutils & avr-libc
      run: sudo apt install gcc-avr binutils-avr avr-libc
    - uses: actions/checkout@v2
    - name: install submodules (u8glib & lufa)
      run: git submodule update --init --recursive
    - name: make
      run: make MCU=atmega328p
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-m328p
        path: fddEMU.hex
        retention-days: 5
